liquid_pairs_aggressive:
  constructor: product
  exit_parameters:
    exit_type: aggressive
    stoploss_limit:
    - 25
    - 50
    - 100
    - 150
    - 200
    takeprofit_limit:
    - 25
    - 50
    - 100
    - 150
    - 200
  filter_snapshot_for_strategy: true
  filter_snapshot_for_traded_account_instrument_pairs: true
  instruments:
  - 100637
  - 100639
  - 100643
  - 100645
  - 100647
  - 100649
  - 100655
  - 100661
  - 100741
  load_instruments_from_snapshot: false
  load_target_accounts_from_snapshot: true
  risk_parameters:
    risk_type: no_risk
  split_by_instrument: true
  strategy_parameters:
    max_pos_qty:
    - 50
    - 100
    - 200
    - 300
    max_pos_qty_buffer: 1.25
    position_lifespan: gfw
    position_lifespan_exit_parameters:
      downtick: 2
      exit_type: chaser
      maxdowntick: 100
      maxuptick: 2
      starttick: 0
      uptick: 2
    strategy_type: internalisation
liquid_pairs_no_hedging:
  constructor: product
  exit_parameters:
    exit_type: aggressive
    stoploss_limit: 10000
    takeprofit_limit: 10000
  filter_snapshot_for_strategy: true
  filter_snapshot_for_traded_account_instrument_pairs: true
  instruments:
  - 100637
  - 100639
  - 100643
  - 100645
  - 100647
  - 100649
  - 100655
  - 100661
  - 100741
  load_instruments_from_snapshot: false
  load_target_accounts_from_snapshot: true
  risk_parameters:
    risk_type: no_risk
  split_by_instrument: true
  strategy_parameters:
    max_pos_qty:
    - 50
    - 100
    - 200
    - 300
    max_pos_qty_buffer: 1.25
    position_lifespan: gfw
    position_lifespan_exit_parameters:
      downtick: 2
      exit_type: chaser
      maxdowntick: 100
      maxuptick: 2
      starttick: 0
      uptick: 2
    strategy_type: internalisation
liquid_pairs_profit_running:
  constructor: product
  exit_parameters:
    cut_ratio: 0.5
    exit_type: profit_running
    min_trade_size: 0.1
    stoploss_limit:
    - 25
    - 50
    - 100
    - 150
    - 200
    takeprofit_limit:
    - 25
    - 50
    - 100
    - 150
    - 200
  filter_snapshot_for_strategy: true
  filter_snapshot_for_traded_account_instrument_pairs: true
  instruments:
  - 100637
  - 100639
  - 100643
  - 100645
  - 100647
  - 100649
  - 100655
  - 100661
  - 100741
  load_instruments_from_snapshot: false
  load_target_accounts_from_snapshot: true
  risk_parameters:
    risk_type: no_risk
  split_by_instrument: true
  strategy_parameters:
    max_pos_qty:
    - 50
    - 100
    - 200
    - 300
    max_pos_qty_buffer: 1.25
    position_lifespan: gfw
    position_lifespan_exit_parameters:
      downtick: 2
      exit_type: chaser
      maxdowntick: 100
      maxuptick: 2
      starttick: 0
      uptick: 2
    strategy_type: internalisation
liquid_pairs_trailing_stoploss:
  constructor: product
  exit_parameters:
    exit_type: trailing_stoploss
    stoploss_limit:
    - 25
    - 50
    - 100
    - 150
    - 200
  filter_snapshot_for_strategy: true
  filter_snapshot_for_traded_account_instrument_pairs: true
  instruments:
  - 100637
  - 100639
  - 100643
  - 100645
  - 100647
  - 100649
  - 100655
  - 100661
  - 100741
  load_instruments_from_snapshot: false
  load_target_accounts_from_snapshot: true
  risk_parameters:
    risk_type: no_risk
  split_by_instrument: true
  strategy_parameters:
    max_pos_qty:
    - 50
    - 100
    - 200
    - 300
    max_pos_qty_buffer: 1.25
    position_lifespan: gfw
    position_lifespan_exit_parameters:
      downtick: 2
      exit_type: chaser
      maxdowntick: 100
      maxuptick: 2
      starttick: 0
      uptick: 2
    strategy_type: internalisation
