calculate_cumulative_daily_pnl: true
event_stream_parameters:
  event_stream_type: event_stream_snapshot
  excl_period: null
  sample_rate: D
  include_eod_snapshot: true
level: mark_to_market
load_starting_positions: false
matching_engine_parameters:
  matching_engine_type: matching_engine_default
matching_method: side_of_book
netting_engine: fifo
process_portfolio: true
simulator: simulator_pool
store_trade_snapshot: true
store_md_snapshot: true
store_order_snapshot: true
store_eod_snapshot: true
uid: ld-int-pt
version: 1
