ldprof_internalisation_relative_in_2:
  constructor: product
  exit_parameters:
    exit_type: aggressive
    stoploss_limit: 80
    takeprofit_limit: 120
  filter_snapshot_for_strategy: true
  filter_snapshot_for_traded_account_instrument_pairs: true
  instruments: &id001
  - 100741
  - 100643
  - 100645
  - 100647
  - 100649
  - 100655
  - 100661
  - 100637
  - 100639
  load_instruments_from_snapshot: false
  load_target_accounts_from_snapshot: true
  relative_simulation:
    comparison_accounts:
    - 445659493
    comparison_accounts_type: internalisation
    direction: in
  risk_parameters:
    risk_type: no_risk
  split_by_instrument: true
  strategy_parameters:
    max_pos_qty: 250
    max_pos_qty_buffer: 1.25
    position_lifespan: gfw
    position_lifespan_exit_parameters:
      downtick: 2
      exit_type: chaser
      maxdowntick: 100
      maxuptick: 2
      starttick: 0
      uptick: 2
    strategy_type: internalisation
ldprof_internalisation_relative_out_2:
  constructor: product
  exit_parameters:
    exit_type: aggressive
    stoploss_limit: 80
    takeprofit_limit: 120
  filter_snapshot_for_strategy: true
  filter_snapshot_for_traded_account_instrument_pairs: true
  instruments: *id001
  load_instruments_from_snapshot: false
  load_target_accounts_from_snapshot: true
  relative_simulation:
    direction: out
  risk_parameters:
    risk_type: no_risk
  split_by_instrument: true
  strategy_parameters:
    max_pos_qty: 250
    max_pos_qty_buffer: 1.25
    position_lifespan: gfw
    position_lifespan_exit_parameters:
      downtick: 2
      exit_type: chaser
      maxdowntick: 100
      maxuptick: 2
      starttick: 0
      uptick: 2
    strategy_type: internalisation
